# Server settings
#address写成了127.0.0.1我试了下只能用127.0.0.1来访问了，ip访问不管用了。注掉了就不限制了
server:
  port: 8086
#  address: 127.0.0.1
  servlet:
    context-path: /hmweb

# SPRING PROFILES
spring:
  # HTTP ENCODING
  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true
  # DATASOURCE
  datasource:
    driverClass: com.mysql.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8
    #url后拼接&useAffectedRows=true  这个加了之后，update的时候如果没有修改字段则返回0，如果不加这个则不管是否更新到数据都返回1
    #即后面这个 url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useAffectedRows=true
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
#这个 type可要可不要，要了就是这个，不要就用默认的
#    type: org.apache.commons.dbcp2.BasicDataSource


#配置mybatis mapper.xml扫描路径
mybatis:
  mapper-locations: classpath*:com/hm/*/service/dao/impl/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#mybatis-pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


